'use client';
import HorizontalGallery from './horizontal-gallery';
import { useEffect, useState } from 'react';
import { ArrowDown, ArrowUpRight, Pause, Play, Mail, Phone, Menu, X } from 'lucide-react';
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from '@/components/ui/accordion';
import { marketingServices, marketingWays, steps, faq } from './offer-data';
import PortfolioGallery from './portfolio-gallery';
import HeroShowcase from './hero-showcase';
import IndustryCardSelector from './industry-card-selector';

const contactEmail = 'junskam@gmail.com';
const contactPhone = '510 875 101';
const contactPhoneHref = 'tel:+48510875101';

export default function Home() {
  const [motion,setMotion]=useState(true);
  const [mobileMenuOpen,setMobileMenuOpen]=useState(false);
  useEffect(()=>{
    const preference=window.matchMedia('(prefers-reduced-motion: reduce)');
    const update=()=>setMotion(!preference.matches);update();preference.addEventListener('change',update);
    return()=>preference.removeEventListener('change',update);
  },[]);
  useEffect(()=>{
    const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target);}}),{threshold:.06});
    document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));return()=>observer.disconnect();
  },[]);
  return <div className={motion?'site':'site motion-paused'}>
    <a href="#portfolio" className="skip-link">Przejdź do portfolio</a>
    <header className="site-header"><a className="wordmark" href="#poczatek" aria-label="Arcysia Marketing — początek" onClick={()=>setMobileMenuOpen(false)}><img className="brand-logo" src="media/arcysia-logo-transparent.png" alt="Arcysia Marketing" width={845} height={400}/></a>{mobileMenuOpen && <button className="menu-backdrop" aria-label="Zamknij menu" onClick={()=>setMobileMenuOpen(false)}/>}<nav id="site-navigation" className={mobileMenuOpen ? "site-nav is-open" : "site-nav"} aria-label="Nawigacja główna"><a href="#poczatek" onClick={()=>setMobileMenuOpen(false)}>Start</a><a href="#marketing" onClick={()=>setMobileMenuOpen(false)}>Oferta</a><a href="#pomysly-dla-branzy" onClick={()=>setMobileMenuOpen(false)}>Pomysły dla branży</a><a href="#portfolio" onClick={()=>setMobileMenuOpen(false)}>Realizacje</a><a href="#wspolpraca" onClick={()=>setMobileMenuOpen(false)}>Jak pracuję</a><a href="#o-mnie" onClick={()=>setMobileMenuOpen(false)}>O mnie</a><a href="#kontakt" onClick={()=>setMobileMenuOpen(false)}>Kontakt</a></nav><div className="header-actions"><button className="motion-toggle" onClick={()=>setMotion(!motion)} aria-pressed={!motion} aria-label={motion?'Wstrzymaj animacje':'Włącz animacje'} title={motion?'Wstrzymaj animacje':'Włącz animacje'}>{motion?<Pause size={17}/>:<Play size={17}/>}</button><button className="menu-toggle" onClick={()=>setMobileMenuOpen(!mobileMenuOpen)} aria-expanded={mobileMenuOpen} aria-controls="site-navigation" aria-label={mobileMenuOpen?'Zamknij menu':'Otwórz menu'}>{mobileMenuOpen?<X size={22}/>:<Menu size={22}/>}</button></div></header>
    <main id="poczatek">
      <section className="hero showcase-hero section-pad" aria-labelledby="hero-title">
        <div className="hero-eyebrow"><span>ARCYSIA / PORTFOLIO MARKETINGOWE</span><span>OBRAZ · SŁOWO · RUCH</span></div>
        <div className="showcase-layout"><div className="showcase-copy"><h1 id="hero-title">Twoja marka.<br/><em>Jasny przekaz.</em></h1><div className="hero-person"><img src="media/marcelina-junska-portrait.png" width={1080} height={1350} alt="Marcelina Juńska" fetchPriority="high"/><span>Cześć, jestem Marcelina.<small>Arcysia Marketing</small></span></div><p>Tworzę strategię, teksty, rolki i grafiki. Prowadzę social media, żeby klienci wiedzieli, co oferujesz, a Tobie zostawało więcej czasu na prowadzenie firmy.</p><div className="intro-actions"><a className="button button-orange" href="#portfolio">Zobacz realizacje <ArrowDown size={19}/></a><a className="showcase-offer-link" href="#kontakt">Porozmawiajmy o Twojej marce <ArrowUpRight size={19}/></a></div></div><HeroShowcase motion={motion}/></div>
      </section>
      <PortfolioGallery motion={motion}/>
      <section id="marketing" className="marketing-section section-pad" aria-labelledby="marketing-title">
        <div className="section-heading reveal"><span className="eyebrow">02 / OFERTA MARKETINGOWA</span><h2 id="marketing-title">Od planu<br/>do <em>publikacji.</em></h2><p className="section-lead">Możesz powierzyć mi jeden projekt albo regularne zadania marketingowe. Nie każda marka potrzebuje tego samego. Dlatego zakres współpracy dopasowuję do sytuacji, celu i możliwości zespołu.</p></div>
        <HorizontalGallery className="services-gallery" label="Oferta marketingowa">{marketingServices.map((service,index)=><article className="service-card" key={service.title}><span className="service-index">{String(index+1).padStart(2,'0')}</span><h3>{service.title}</h3><p>{service.description}</p><p className="service-audience">{service.audience}</p><div className="service-result"><span>CO OTRZYMUJESZ</span><p>{service.result}</p></div><Accordion className="service-accordion"><AccordionItem value="scope"><AccordionTrigger aria-label={`Zobacz zakres: ${service.title}`}>Co przygotowuję</AccordionTrigger><AccordionContent className="service-details"><ul>{service.scope.map(item=><li key={item}>{item}</li>)}</ul>{service.note&&<p className="service-note">{service.note}</p>}</AccordionContent></AccordionItem></Accordion></article>)}</HorizontalGallery>
        <div className="ways-block"><div className="small-heading"><span className="eyebrow">ZAKRES DOPASOWANY DO CIEBIE</span><h3>Jeden projekt czy regularna pomoc?</h3></div><div className="ways-grid">{marketingWays.map((way,index)=><article key={way.title}><span className="way-index">0{index+1}</span><h4>{way.title}</h4><p>{way.description}</p></article>)}</div><p className="terms-note">Zakres, termin i wycenę ustalam indywidualnie. Przed rozpoczęciem współpracy określamy materiały do przygotowania, liczbę poprawek i sposób przekazania gotowych plików.</p></div>
      </section>
      <section className="audience-section section-pad" aria-labelledby="audience-title">
        <div className="section-heading"><span className="eyebrow">DLA KOGO PRACUJĘ</span><h2 id="audience-title">Masz markę.<br/>Nie musisz robić <em>wszystkiego.</em></h2></div>
        <div className="audience-copy"><p>Wierzę, że każda firma, marka osobista i lokalny biznes potrzebują być widoczne. Social media to dziś jedno z podstawowych miejsc, w których klienci poznają ofertę, wyrabiają sobie opinię i decydują o kontakcie.</p><p>Nie zawsze masz czas, pomysł albo wiedzę, żeby regularnie się tym zajmować. Pomagam znaleźć kierunek i przejmuję część zadań — od planowania po publikację. Dzięki temu komunikacja ma swój rytm i wspiera to, co chcesz osiągnąć w biznesie.</p></div>
        <ul className="audience-list">{['Marki osobiste, eksperci i usługodawcy', 'Beauty, firmy stolarskie i wnętrzarskie', 'Restauracje, kawiarnie i lokalne biznesy', 'Agencje marketingowe i eventowe', 'Marki edukacyjne', 'Firmy zaczynające lub porządkujące social media'].map(item=><li key={item}>{item}</li>)}</ul>
        <p className="section-lead">To przykłady marek, którym mogę pomóc. Ważniejsza od branży jest Twoja sytuacja: co oferujesz, do kogo chcesz dotrzeć i jak odbiorcy mają zapamiętać Twoją markę.</p>
      </section>
      <IndustryCardSelector />
      <section className="about-section section-pad marketing-about" id="o-mnie" aria-labelledby="about-title"><figure className="about-photo"><img src="media/marcelina-junska-portrait.png" width={1080} height={1350} alt="Marcelina Juńska, twórczyni Arcysia Marketing" loading="lazy"/></figure><div className="about-copy"><span className="eyebrow">04 / O MNIE</span><h2 id="about-title">Marcelina<br/><em>Juńska.</em></h2><p>Łączę strategię, tworzenie treści i organizację. Potrafię ustalić kierunek komunikacji, przełożyć go na teksty, grafiki i wideo, a potem dopilnować realizacji.</p><p>Jako freelancerka wspieram agencję marketingową UX, markę osobistą, kancelarię oraz marki z branży beauty i meblarskiej. Znam też projekty edukacyjne i eventowe. Lubię porządkować zadania tak, żeby dobry pomysł doczekał się publikacji.</p><p>Ważną częścią mojej pracy jest też łączenie marek. Pomagam znaleźć partnerów, których oferta i odbiorcy do siebie pasują, oraz zaplanować wspólne treści, akcje promocyjne czy wydarzenia. Dbam o pomysł i ustalenia, żeby każda strona wiedziała, co wnosi do współpracy i co może dzięki niej zyskać.</p><div className="about-events"><h3>Za kreatywnością stoi dobry plan.</h3><p>Mam ponad 3 lata doświadczenia w projektach marketingowych i eventowych. Pracowałam przy organizacji ponad 40 konferencji i wydarzeń, w tym projektów do 600 uczestników.</p><p>Koordynowałam konferencje z branży farmaceutycznej w całej Polsce: harmonogramy, budżety, partnerów i podwykonawców. To doświadczenie pomaga mi planować pracę i doprowadzać projekty do końca.</p></div></div></section>
      <section className="process-section section-pad" id="wspolpraca" aria-labelledby="process-title"><div className="section-heading reveal"><span className="eyebrow">05 / OD ROZMOWY DO REALIZACJI</span><h2 id="process-title">Jak wygląda <em>współpraca?</em></h2><p className="section-lead">Najpierw sprawdzam, co chcesz osiągnąć i do kogo mówisz. Dopiero potem dobieram tematy, formaty i sposób publikacji.</p></div><ol className="steps-grid">{steps.map((step,index)=><li key={step.title}><span className="step-number">0{index+1}</span><h3>{step.title}</h3><p>{step.description}</p></li>)}</ol><div className="faq-layout"><div className="small-heading"><span className="eyebrow">FAQ</span><h3>Warto wiedzieć.</h3></div><Accordion className="faq-accordion">{faq.map((item,index)=><AccordionItem key={item.question} value={`faq-${index}`}><AccordionTrigger>{item.question}</AccordionTrigger><AccordionContent><p>{item.answer}</p></AccordionContent></AccordionItem>)}</Accordion></div></section>
      <section className="contact-section section-pad" id="kontakt" aria-labelledby="contact-title"><div><span className="eyebrow">06 / KONTAKT</span><h2 id="contact-title">Opowiedz mi,<br/>co <em>planujesz.</em></h2><p className="contact-lead">Nie musisz mieć gotowego briefu. Napisz, co chcesz rozwinąć, uporządkować albo pokazać lepiej.</p><p className="contact-lead">Możemy zacząć od pojedynczego projektu, strategii, audytu czy konsultacji — albo porozmawiać o stałym wsparciu.</p><div className="contact-links"><a className="button button-orange" href={`mailto:${contactEmail}`}>Opowiedz mi o swojej marce <Mail size={21} aria-hidden="true"/></a><dl className="contact-details"><div><dt>E-mail</dt><dd><a href={`mailto:${contactEmail}`}><Mail size={20} aria-hidden="true"/>{contactEmail}</a></dd></div><div><dt>Telefon</dt><dd><a href={contactPhoneHref}><Phone size={20} aria-hidden="true"/>{contactPhone}</a></dd></div></dl></div></div><aside className="contact-brief"><span className="eyebrow">DO PRZYGOTOWANIA WYCENY</span><h3>Kilka słów<br/>na dobry początek.</h3><ul><li>Co planujesz i jaki jest Twój cel?</li><li>Jaki zakres wsparcia Cię interesuje?</li><li>Jaki termin i budżet bierzesz pod uwagę?</li><li>Gdzie chcesz publikować swoje materiały?</li></ul></aside></section>
    </main>
    <footer><a className="footer-wordmark" href="#poczatek" aria-label="Arcysia — wróć do początku">arcysia</a><div className="footer-bottom"><p>© 2026 Marcelina Juńska · Arcysia Marketing</p><span>POSTY · ROLKI · KOMUNIKACJA</span><a href="#poczatek">Do góry <ArrowUpRight size={18}/></a></div></footer>
  </div>;
}
